// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnvnzzwseyauppinormw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudm56endzZXlhdXBwaW5vcm13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NzAzNzMsImV4cCI6MjA3NDM0NjM3M30.oWwikGEGy51uW4OQIrmQg5gE9NW9w-sgAyOC5q5FsJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});